apiVersion: apps/v1
kind: Deployment
metadata:
  name: honysite
spec:
  replicas: 4
  selector:
    matchLabels:
      app: honysite
  template:
    metadata:
      labels:
        app: honysite
    spec:
      containers:
      - name: honysite
        image: sachindev99/honysite:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
